# -*- coding: utf-8 -*-
"""gloss2id.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbWokuLv4onvi1tmiHE30Zec0AcFE4uA
"""

import pickle

with open('/content/gloss2ids.pkl', 'rb') as f:
    data = pickle.load(f)
print(data)
print(len(data))

import pickle

with open('/content/gloss2ids_old.pkl', 'rb') as f:
    data1 = pickle.load(f)
print(data1)
print(len(data1))



import pickle

with open('/content/map_ids.pkl', 'rb') as f:
    data2 = pickle.load(f)
print(data2)
print(len(data2))

!pip install nltk
!python -m nltk.downloader punkt
import nltk
from nltk.tokenize import word_tokenize

# Read sentences from a file (replace 'myfile.txt' with your file path)
with open('Sign sentence.txt', 'r', encoding='utf-8') as fin:
    sentences = fin.read()

# Tokenize the sentences into words
tokens = word_tokenize(sentences)

# Print the tokens
print(tokens)
print(len(tokens))

tokens = list(dict.fromkeys(tokens))
print(tokens)
print(len(tokens))
items  = ['<mask>', '<unk>', '</s>', '<pad>', '<s>']
for item in items:
    tokens.insert(0, item)

print(tokens)

alignment_ids = {gloss: i for i, gloss in enumerate(tokens)}

print("Alignment IDs:")
gloss2id={}
for gloss, alignment_id in alignment_ids.items():
    gloss2id[gloss]=alignment_id
    print(f"{gloss}: {alignment_id}")

import pickle
print(gloss2id)
with open('/content/gloss2id.pkl', 'wb') as file:
    pickle.dump(gloss2id, file)

